const mongoose=require("mongoose")

const addproperties=new mongoose.Schema({
    propertyName:{
        type:String,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    location:{
        type:String,
    },
    builderName:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    propertyType:{
        type:String,
        required:true
    },
    propertyStatus:{
        type:String,
        required:true
    },
    pricePerSquareFeet:{
        type:String,
        required:true
    },
    areaSquareFeetFrom:{
        type:Number,
        required:true
    },
    areaSquareFeetTo:{
        type:Number,
        required:true
    },
    priceFromInWords:{
        type:String,
        required:true
    },
    priceToInWords:{
        type:String,
        required:true
    },
    priceFromInNumber:{
        type:Number,
        required:true
    },
    priceToInNumber:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    videoUrl:{
        type:String,
        required:true
    },
    yearsOfConstruction:{
        type:String,
        required:true
    },
    listingStatus:{
        type:String,
        required:true
    },
    upload:{
        type:[String],
        required:true
    },
    amenities:{
        type:[String],
        required:true
    },
    additionalInfo:{
        type:[String],
        required:true
    },
    builderDescription:{
        type:String
    },
    nearbyPlaces:{
        type:[String],
        default:[]
    },
    mainImage:{
        type:String
    }
})
module.exports=mongoose.model('addproperties',addproperties);